{
  allDataTypes {
    nodes {
      nameGerman
      propertyCollectionsByDataType {
        totalCount
      }
      relationCollectionsByDataType {
        totalCount
      }
      categoriesByDataType {
        totalCount
      }
    }
  }
}
