{
  allCategories {
    totalCount
    nodes {
      name
      taxonomiesByCategory(condition: {category: "Fauna"}) {
        totalCount
        nodes {
          name
          isCategoryStandard
          taxonomyObjectLevel1(name: "CSCF (2009)") {
            totalCount
            nodes {
              id
              name
              taxonomyObjectsByParentId(condition: {parentId: "eb06d369-1f58-4d99-8094-521872e05b21"}) {
                totalCount
                nodes {
                  id
                  name
                  taxonomyObjectsByParentId(condition: {parentId: "1246ff73-170a-411e-9598-91606c50e516"}) {
                    totalCount
                    nodes {
                      id
                      name
                      taxonomyObjectsByParentId(condition: {parentId: "e9cdb7a4-5335-4e1d-b25f-c222084a9ba5"}) {
                        totalCount
                        nodes {
                          id
                          name
                          taxonomyObjectsByParentId(condition: {parentId: "055338cf-bb74-441c-a41d-6914bdebd748"}) {
                            totalCount
                            nodes {
                              id
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
