/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TreeTaxonomyObjectsByTaxonomyQuery.graphql
 * @generated SignedSource<<3e1f63da7a3e7b11a6c4226103f710bb>>
 * @relayHash e75c69e26f8b8c4d81f7d733114c09f0
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query TreeTaxonomyObjectsByTaxonomyQuery {
  taxonomyByName(name: "CSCF (2009)") {
    id
    name
    category
    taxonomyObjectsByTaxonomyId {
      totalCount
      nodes {
        id
        name
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "TreeTaxonomyObjectsByTaxonomyQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Literal",
            "name": "name",
            "value": "CSCF (2009)",
            "type": "String!"
          }
        ],
        "concreteType": "Taxonomy",
        "name": "taxonomyByName",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "category",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "TaxonomyObjectsConnection",
            "name": "taxonomyObjectsByTaxonomyId",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "totalCount",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "TaxonomyObject",
                "name": "nodes",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": "taxonomyByName{\"name\":\"CSCF (2009)\"}"
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "TreeTaxonomyObjectsByTaxonomyQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "TreeTaxonomyObjectsByTaxonomyQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Literal",
            "name": "name",
            "value": "CSCF (2009)",
            "type": "String!"
          }
        ],
        "concreteType": "Taxonomy",
        "name": "taxonomyByName",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "category",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "TaxonomyObjectsConnection",
            "name": "taxonomyObjectsByTaxonomyId",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "totalCount",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "TaxonomyObject",
                "name": "nodes",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": "taxonomyByName{\"name\":\"CSCF (2009)\"}"
      }
    ]
  },
  "text": "query TreeTaxonomyObjectsByTaxonomyQuery {\n  taxonomyByName(name: \"CSCF (2009)\") {\n    id\n    name\n    category\n    taxonomyObjectsByTaxonomyId {\n      totalCount\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
