/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TreeFilter.graphql
 * @generated SignedSource<<f9eab4dd567fee21365cf26ce890eb00>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type TreeFilter = {|
  +propertyCollectionByPropertyName: ?{|
    +nodes: ?$ReadOnlyArray<?{|
      +id: any;
      +name: string;
    |}>;
  |};
  +relationCollectionByRelationName: ?{|
    +nodes: ?$ReadOnlyArray<?{|
      +id: any;
      +name: string;
    |}>;
  |};
  +taxonomyObjectByTaxonomyObjectName: ?{|
    +nodes: ?$ReadOnlyArray<?{|
      +id: any;
      +name: string;
    |}>;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "TreeFilter",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "propertyName",
          "value": "rot",
          "type": "String"
        }
      ],
      "concreteType": "PropertyCollectionByPropertyNameConnection",
      "name": "propertyCollectionByPropertyName",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PropertyCollection",
          "name": "nodes",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "propertyCollectionByPropertyName{\"propertyName\":\"rot\"}"
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "relationName",
          "value": "2010",
          "type": "String"
        }
      ],
      "concreteType": "RelationCollectionByRelationNameConnection",
      "name": "relationCollectionByRelationName",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "RelationCollection",
          "name": "nodes",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "relationCollectionByRelationName{\"relationName\":\"2010\"}"
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "taxonomyObjectName",
          "value": "hyla",
          "type": "String"
        }
      ],
      "concreteType": "TaxonomyObjectByTaxonomyObjectNameConnection",
      "name": "taxonomyObjectByTaxonomyObjectName",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "TaxonomyObject",
          "name": "nodes",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "taxonomyObjectByTaxonomyObjectName{\"taxonomyObjectName\":\"hyla\"}"
    }
  ],
  "type": "Query"
};

module.exports = fragment;
