query AppQueryQuery(
  $existsLevel2Pc: Boolean!
  $level2Pc: String!
  $existsLevel2Taxonomy: Boolean!
  $level2Taxonomy: String!
  $existsLevel3: Boolean!
  $level3Taxonomy: String!
  $existsLevel4: Boolean!
  $level4Taxonomy: Uuid!
  $existsLevel5: Boolean!
  $level5Taxonomy: Uuid!
  $existsLevel6: Boolean!
  $level6Taxonomy: Uuid!
  $existsLevel7: Boolean!
  $level7Taxonomy: Uuid!
  $existsLevel8: Boolean!
  $level8Taxonomy: Uuid!
  $existsLevel9: Boolean!
  $level9Taxonomy: Uuid!
  $existsLevel10: Boolean!
  $level10Taxonomy: Uuid!
  $activeTaxonomyObjectId: Uuid!
  $existsActiveTaxonomyObject: Boolean!
  $existsUrlFromTOId: Boolean!
  $urlFromTOId: Uuid!
  $existsTreeFilterText: Boolean!
  $treeFilterText: String!
  $queryGroups: Boolean!
  $queryExportCategories: Boolean!
  $exportCategories: [String]
) {
  allCategories {
    totalCount
  }
  allPropertyCollections {
    totalCount
  }
  propertyCollectionByDataType(datatype: $level2Pc)
    @include(if: $existsLevel2Pc) {
    nodes {
      id
      name
      propertyCollectionObjectsByPropertyCollectionId {
        totalCount
      }
    }
  }
  level2Taxonomy: categoryByDataType(datatype: $level2Taxonomy)
    @include(if: $existsLevel2Taxonomy) {
    nodes {
      id
      name
      taxonomyByCategory {
        totalCount
      }
    }
  }
  level3Taxonomy: categoryByName(name: $level3Taxonomy)
    @include(if: $existsLevel3) {
    taxonomiesByCategory {
      nodes {
        id
        name
        taxonomyObjectLevel1 {
          totalCount
        }
      }
    }
  }
  level4Taxonomy: taxonomyById(id: $level4Taxonomy)
    @include(if: $existsLevel4) {
    taxonomyObjectLevel1 {
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level5Taxonomy: taxonomyObjectById(id: $level5Taxonomy)
    @include(if: $existsLevel5) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level6Taxonomy: taxonomyObjectById(id: $level6Taxonomy)
    @include(if: $existsLevel6) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level7Taxonomy: taxonomyObjectById(id: $level7Taxonomy)
    @include(if: $existsLevel7) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level8Taxonomy: taxonomyObjectById(id: $level8Taxonomy)
    @include(if: $existsLevel8) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level9Taxonomy: taxonomyObjectById(id: $level9Taxonomy)
    @include(if: $existsLevel9) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level10Taxonomy: taxonomyObjectById(id: $level10Taxonomy)
    @include(if: $existsLevel10) {
    objectsByParentId {
      totalCount
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  taxonomyObjectById(id: $activeTaxonomyObjectId)
    @include(if: $existsActiveTaxonomyObject) {
    objectByObjectId {
      id
      taxonomyObjectsByObjectId {
        totalCount
        nodes {
          taxonomyByTaxonomyId {
            id
            name
            description
            links
            lastUpdated
            organizationByOrganizationId {
              name
            }
          }
          id
          name
          properties
          synonymsByObjectId {
            totalCount
            nodes {
              taxonomyObjectIdSynonym
              objectByObjectIdSynonym {
                id
                name
                properties
                taxonomyByTaxonomyId {
                  name
                  description
                  links
                  lastUpdated
                  organizationByOrganizationId {
                    name
                  }
                }
                objectByObjectId {
                  id
                  propertyCollectionObjectsByObjectId {
                    totalCount
                    nodes {
                      objectId
                      propertyCollectionId
                      properties
                      propertyCollectionByPropertyCollectionId {
                        name
                        description
                        links
                        combining
                        lastUpdated
                        termsOfUse
                        importedBy
                        organizationByOrganizationId {
                          name
                        }
                        userByImportedBy {
                          name
                          email
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      propertyCollectionObjectsByObjectId {
        totalCount
        nodes {
          objectId
          propertyCollectionId
          properties
          propertyCollectionByPropertyCollectionId {
            name
            description
            links
            combining
            lastUpdated
            termsOfUse
            importedBy
            organizationByOrganizationId {
              name
            }
            userByImportedBy {
              name
              email
            }
          }
        }
      }
    }
  }
  urlFromTO: taxonomyObjectById(id: $urlFromTOId)
    @include(if: $existsUrlFromTOId) {
    id
    taxonomyObjectByParentId {
      id
      taxonomyObjectByParentId {
        id
        taxonomyObjectByParentId {
          id
          taxonomyObjectByParentId {
            id
            taxonomyObjectByParentId {
              id
              taxonomyObjectByParentId {
                id
              }
            }
          }
        }
      }
    }
    taxonomyByTaxonomyId {
      id
      categoryByCategory {
        name
        dataType
      }
    }
  }
  filterSuggestionsPC: propertyCollectionByPropertyName(
    propertyName: $treeFilterText
  ) @include(if: $existsTreeFilterText) {
    totalCount
    nodes {
      id
      name
    }
  }
  filterSuggestionsTO: objectByObjectName(
    taxonomyObjectName: $treeFilterText
  ) @include(if: $existsTreeFilterText) {
    totalCount
    nodes {
      id
      name
    }
  }
  allCategories @include(if: $queryGroups) {
    nodes {
      name
    }
  }
  pcoPropertiesByCategoriesFunction(categories: $exportCategories)
    @include(if: $queryExportCategories) {
    nodes {
      propertyCollectionName
      propertyName
      jsontype
      count
    }
  }
}

// Beispiel Achillea moschata Wulfen:
{
  "existsLevel2Pc": false,
  "level2Pc": "99999999-9999-9999-9999-999999999999",
  "existsLevel2Taxonomy": true,
  "level2Taxonomy": "Taxonomien",
  "existsLevel3": true,
  "level3Taxonomy": "Flora",
  "existsLevel4": true,
  "level4Taxonomy": "2339fb91-5d0d-11e7-84b7-87417ccd9781",
  "existsLevel5": true,
  "level5Taxonomy": "326901c3-5d0d-11e7-84b7-87417ccd9781",
  "existsLevel6": false,
  "level6Taxonomy": "327732ce-5d0d-11e7-84b7-87417ccd9781",
  "existsLevel7": false,
  "level7Taxonomy": "32f82250-5d0d-11e7-84b7-87417ccd9781",
  "existsLevel8": false,
  "level8Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel9": false,
  "level9Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel10": false,
  "level10Taxonomy": "99999999-9999-9999-9999-999999999999",
  "activeTaxonomyObjectId": "32f82250-5d0d-11e7-84b7-87417ccd9781",
  "existsActiveTaxonomyObject": true,
  "existsUrlFromTOId": false,
  "urlFromTOId": "99999999-9999-9999-9999-999999999999",
  "existsTreeFilterText": false,
  "treeFilterText": "ZZZZ",
  "queryGroups": false,
  "queryExportCategories": false,
  "exportCategories": []
}

// Beispiel Lebensraum:
{
  "existsLevel2Pc": false,
  "level2Pc": "99999999-9999-9999-9999-999999999999",
  "existsLevel2Taxonomy": true,
  "level2Taxonomy": "Taxonomien",
  "existsLevel3": true,
  "level3Taxonomy": "Lebensräume",
  "existsLevel4": true,
  "level4Taxonomy": "8946c88f-56bb-11e7-95e1-7338d9fb04be",
  "existsLevel5": true,
  "level5Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel6": false,
  "level6Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel7": false,
  "level7Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel8": false,
  "level8Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel9": false,
  "level9Taxonomy": "99999999-9999-9999-9999-999999999999",
  "existsLevel10": false,
  "level10Taxonomy": "99999999-9999-9999-9999-999999999999",
  "activeTaxonomyObjectId": "99999999-9999-9999-9999-999999999999",
  "existsActiveTaxonomyObject": false,
  "existsUrlFromTOId": false,
  "urlFromTOId": "99999999-9999-9999-9999-999999999999",
  "existsTreeFilterText": false,
  "treeFilterText": "ZZZZ",
  "queryGroups": false,
  "queryExportCategories": false,
  "exportCategories": []
}
