query AppQueryQuery($existsLevel2Pc: Boolean!, $notExistsLevel2Pc: Boolean!, $existsLevel2Taxonomy: Boolean!, $existsLevel3: Boolean!, $level3Taxonomy: String!, $existsLevel4: Boolean!, $level4Taxonomy: Uuid!, $level4TaxonomyPossibleNull: Uuid, $existsLevel5: Boolean!, $level5Taxonomy: Uuid!, $existsLevel6: Boolean!, $level6Taxonomy: Uuid!, $existsLevel7: Boolean!, $level7Taxonomy: Uuid!, $existsLevel8: Boolean!, $level8Taxonomy: Uuid!, $existsLevel9: Boolean!, $level9Taxonomy: Uuid!, $existsLevel10: Boolean!, $level10Taxonomy: Uuid!, $treeFilterId: Uuid!, $existsTreeFilterId: Boolean!, $treeFilterText: String!, $queryGroups: Boolean!, $queryExportTaxonomies: Boolean!, $exportTaxonomies: [String]) {
  allCategories {
    totalCount
  }
  allPropertyCollections @include(if: $notExistsLevel2Pc) {
    totalCount
  }
  allPropertyCollections @include(if: $existsLevel2Pc) {
    totalCount
    nodes {
      id
      name
      propertyCollectionObjectsByPropertyCollectionId {
        totalCount
      }
    }
  }
  level2Taxonomy: categoriesOfTaxonomiesFunction @include(if: $existsLevel2Taxonomy) {
    nodes {
      id
      name
      count
    }
  }
  level3Taxonomy: taxonomiesOfCategory(category: $level3Taxonomy) @include(if: $existsLevel3) {
    nodes {
      id
      name
      objectLevel1(taxonomyId: $level4TaxonomyPossibleNull) {
        totalCount
      }
    }
  }
  level4Taxonomy: taxonomyById(id: $level4Taxonomy) @include(if: $existsLevel4) {
    objectLevel1(taxonomyId: $level4TaxonomyPossibleNull) {
      nodes {
        id
        name
        objectsByParentId {
          totalCount
        }
      }
    }
  }
  level5Taxonomy: objectById(id: $level5Taxonomy) @include(if: $existsLevel5) {
    ...ObjektLevel5AndUp
  }
  level6Taxonomy: objectById(id: $level6Taxonomy) @include(if: $existsLevel6) {
    ...ObjektLevel5AndUp
  }
  level7Taxonomy: objectById(id: $level7Taxonomy) @include(if: $existsLevel7) {
    ...ObjektLevel5AndUp
  }
  level8Taxonomy: objectById(id: $level8Taxonomy) @include(if: $existsLevel8) {
    ...ObjektLevel5AndUp
  }
  level9Taxonomy: objectById(id: $level9Taxonomy) @include(if: $existsLevel9) {
    ...ObjektLevel5AndUp
  }
  level10Taxonomy: objectById(id: $level10Taxonomy) @include(if: $existsLevel10) {
    ...ObjektLevel5AndUp
  }
  objectUrlData: objectById(id: $treeFilterId) @include(if: $existsTreeFilterId) {
    id
    categoryByCategory {
      id
      name
      dataType
    }
    objectByParentId {
      id
      objectByParentId {
        id
        objectByParentId {
          id
          objectByParentId {
            id
            objectByParentId {
              id
              objectByParentId {
                id
              }
            }
          }
        }
      }
    }
    taxonomyByTaxonomyId {
      id
    }
  }
  filterSuggestionsPC: propertyCollectionByPropertyName(propertyName: $treeFilterText) {
    nodes {
      id
      name
    }
  }
  filterSuggestionsTO: objectByObjectName(objectName: $treeFilterText) {
    nodes {
      id
      name
    }
  }
  allCategories @include(if: $queryGroups) {
    nodes {
      id
      name
    }
  }
  pcoPropertiesByTaxonomiesFunction(categories: $exportTaxonomies) @include(if: $queryExportTaxonomies) {
    nodes {
      propertyCollectionName
      propertyName
      jsontype
      count
    }
  }
}

fragment ObjektLevel5AndUp on Object {
  id
  objectsByParentId {
    nodes {
      id
      name
      objectsByParentId {
        totalCount
      }
    }
  }
}

// Beispiel, das nicht funktioniert in app:
{
  "existsLevel2Pc":false,
  "existsLevel2Taxonomy":true,
  "existsLevel3":false,
  "existsLevel4":false,
  "existsLevel5":false,
  "existsLevel6":false,
  "existsLevel7":false,
  "existsLevel8":false,
  "existsLevel9":false,
  "existsLevel10":false,
  "existsTreeFilterId":true,
  "exportTaxonomies":[],
  "level3Taxonomy":"none",
  "level4Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level4TaxonomyPossibleNull":null,
  "level5Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level6Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level7Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level8Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level9Taxonomy":"99999999-9999-9999-9999-999999999999",
  "level10Taxonomy":"99999999-9999-9999-9999-999999999999",
  "notExistsLevel2Pc":true,
  "queryExportTaxonomies":false,
  "queryGroups":false,
  "treeFilterId":"14bd613c-1f03-4907-b7af-7b590fdca42c",
  "treeFilterText":"Canis lupus Linnaeus, 1758 (Wolf)"
}

// Beispiel 10: Magerwiese mit 1 Schnitt extensiv:
{
  "activeObjectId": "a3741a61-8147-4596-9ba4-d9ab5672f530",
  "existsActiveObject": true,
  "existsLevel2Pc": false,
  "existsLevel2Taxonomy": true,
  "existsLevel3": true,
  "existsLevel4": true,
  "existsLevel5": true,
  "existsLevel6": false,
  "existsLevel7": false,
  "existsLevel8": false,
  "existsLevel9": false,
  "existsLevel10": false,
  "existsUrlFromTOId": false,
  "exportTaxonomies": [],
  "level3Taxonomy": "Lebensräume",
  "level4Taxonomy": "69d34753-445b-4c55-b3b7-e570f7dc1819",
  "level4TaxonomyPossibleNull": "69d34753-445b-4c55-b3b7-e570f7dc1819",
  "level5Taxonomy": "a3741a61-8147-4596-9ba4-d9ab5672f530",
  "level6Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level7Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level8Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level9Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level10Taxonomy": "99999999-9999-9999-9999-999999999999",
  "notExistsLevel2Pc": true,
  "queryExportTaxonomies": false,
  "queryGroups": false,
  "treeFilterText": "Achillea moschata",
  "urlFromTOId": "99999999-9999-9999-9999-999999999999"
}
// example acipensiformes
{
  "activeObjectId": "a9226760-696f-11e7-b712-f90bfedd3cfd",
  "existsActiveObject": true,
  "existsLevel2Pc": false,
  "existsLevel2Taxonomy": true,
  "existsLevel3": true,
  "existsLevel4": true,
  "existsLevel5": true,
  "existsLevel6": true,
  "existsLevel7": true,
  "existsLevel8": false,
  "existsLevel9": false,
  "existsLevel10": false,
  "existsUrlFromTOId": false,
  "exportTaxonomies": [],
  "level3Taxonomy": "Fauna",
  "level4Taxonomy": "a8f11e30-696f-11e7-b712-f90bfedd3cfd",
  "level4TaxonomyPossibleNull": "a8f11e30-696f-11e7-b712-f90bfedd3cfd",
  "level5Taxonomy": "a8f6c380-696f-11e7-b712-f90bfedd3cfd",
  "level6Taxonomy": "a8fdc860-696f-11e7-b712-f90bfedd3cfd",
  "level7Taxonomy": "a9226760-696f-11e7-b712-f90bfedd3cfd",
  "level8Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level9Taxonomy": "99999999-9999-9999-9999-999999999999",
  "level10Taxonomy": "99999999-9999-9999-9999-999999999999",
  "notExistsLevel2Pc": true,
  "queryExportTaxonomies": false,
  "queryGroups": false,
  "treeFilterText": "ZZZZ",
  "urlFromTOId": "99999999-9999-9999-9999-999999999999"
}
